---
title: "Captstone Project Proposal"
Author: Linh T. Pham

EUI is defined as energy per square foot per year. It’s calculated by dividing the total energy consumed by the building in one year (measured in kBtu) by the total gross floor area of the building. A low EUI indicates good energy performance.
My client is The San Francisco Public Utilities Commission
First, I would like to identify which building category has the lowest and highest energy performance. 
GGP—Murphy Millwright’s Cottage has the highest EUI. The building is belonging to recreational category. On the observation, this building category produces higher EUI, which range from 300-600 EUI. 
Secondly, I want to find out if the area of a building can impact on energy consumption. From the finding, the airport has the largest area but it produces less EUI than other building categories. The relationship between building area and EUI is not really correlated. 
Finally, building’s age is also contributing to EUI’s level. The oldest building (GGP—Murphy Millwright’s Cottage) generates the highest amount of EUI. 





